# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_img', models.ImageField(default='images/ipad.jpg', upload_to='images/')),
                ('price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=100)),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
